all:
	javac -target 1.6 -g -d ./bin/ \
src/ca/mitmaro/ldb/Application.java \
src/ca/mitmaro/ldb/CommandLineInterface.java \
src/ca/mitmaro/ldb/lang/StringUtils.java \
src/ca/mitmaro/ldb/entity/List.java \
src/ca/mitmaro/ldb/entity/SoftReferenceList.java \
src/ca/mitmaro/ldb/entity/Author.java \
src/ca/mitmaro/ldb/entity/Journal.java \
src/ca/mitmaro/ldb/entity/Publication.java \
src/ca/mitmaro/ldb/entity/Paper.java \
src/ca/mitmaro/ldb/entity/Volume.java \
src/ca/mitmaro/ldb/command/BaseCommand.java \
src/ca/mitmaro/ldb/command/AddPaper.java \
src/ca/mitmaro/ldb/command/AddReference.java \
src/ca/mitmaro/ldb/command/Exit.java \
src/ca/mitmaro/ldb/command/Help.java \
src/ca/mitmaro/ldb/command/ListPaper.java \
src/ca/mitmaro/ldb/command/ListReference.java \
src/ca/mitmaro/ldb/command/LoadPaper.java \
src/ca/mitmaro/ldb/command/LoadReference.java \
src/ca/mitmaro/ldb/command/PrintPaper.java \
src/ca/mitmaro/ldb/command/PrintReference.java \
src/ca/mitmaro/ldb/command/PrintWorkingPaper.java \
src/ca/mitmaro/ldb/command/SetWorkingPaper.java \
src/ca/mitmaro/ldb/EntityManager.java \
src/LDB.java
