all:
	javac -target 1.6 -g -d ./bin/ \
src/ca/mitmaro/lang/StringUtils.java \
src/ca/mitmaro/commandline/help/Message.java \
src/ca/mitmaro/commandline/help/System.java \
src/ca/mitmaro/commandline/term/Terminal.java \
src/ca/mitmaro/commandline/userinterface/TextBased.java \
src/ca/mitmaro/commandline/userinterface/NumberedMenu.java \
src/ca/mitmaro/commandline/userinterface/YesNoQuestion.java \
src/ca/mitmaro/commandline/userinterface/Prompt.java \
src/ca/mitmaro/commandline/userinterface/SimplePrompt.java \
src/ca/mitmaro/commandline/userinterface/FilePrompt.java \
src/ca/mitmaro/commandline/userinterface/ExistentFilePrompt.java \
src/ca/mitmaro/commandline/command/Command.java \
src/ca/mitmaro/commandline/command/Help.java \
src/ca/mitmaro/commandline/command/Exit.java \
src/ca/mitmaro/commandline/CommandLine.java \
src/ca/mitmaro/mips/processor/ALU.java \
src/ca/mitmaro/mips/processor/controller/BranchController.java \
src/ca/mitmaro/mips/processor/ControlUnit.java \
src/ca/mitmaro/mips/processor/DataMemory.java \
src/ca/mitmaro/mips/processor/InstructionMemory.java \
src/ca/mitmaro/mips/processor/Memory.java \
src/ca/mitmaro/mips/processor/Multiplexer.java \
src/ca/mitmaro/mips/processor/RegisterFile.java \
src/ca/mitmaro/mips/processor/RegisterMultiplexer.java \
src/ca/mitmaro/mips/MIPS.java \
src/ca/mitmaro/mips/command/LoadMemoryDump.java \
src/ca/mitmaro/mips/command/LoadProgram.java \
src/ca/mitmaro/mips/command/PrintRegisters.java \
src/ca/mitmaro/mips/command/Run.java \
src/ca/mitmaro/mips/MIPSCommandLine.java \
src/MIPSSim.java
