all:
	javac -target 1.6 -g -d ./bin/ \
src/ca/mitmaro/lang/StringUtils.java \
src/ca/mitmaro/commandline/help/Message.java \
src/ca/mitmaro/commandline/help/System.java \
src/ca/mitmaro/commandline/term/Terminal.java \
src/ca/mitmaro/commandline/userinterface/TextBased.java \
src/ca/mitmaro/commandline/userinterface/NumberedMenu.java \
src/ca/mitmaro/commandline/userinterface/YesNoQuestion.java \
src/ca/mitmaro/commandline/userinterface/Prompt.java \
src/ca/mitmaro/commandline/userinterface/SimplePrompt.java \
src/ca/mitmaro/commandline/userinterface/FilePrompt.java \
src/ca/mitmaro/commandline/userinterface/ExistentFilePrompt.java \
src/ca/mitmaro/commandline/command/Command.java \
src/ca/mitmaro/commandline/command/Help.java \
src/ca/mitmaro/commandline/command/Exit.java \
src/ca/mitmaro/commandline/CommandLine.java \
src/ca/mitmaro/imdb/command/LoadRecommendation.java \
src/ca/mitmaro/imdb/command/ListRecommendationLists.java \
src/ca/mitmaro/imdb/command/MergeRecommendationList.java \
src/ca/mitmaro/imdb/command/SearchRecommendationList.java \
src/ca/mitmaro/imdb/command/DisplayRecommendationList.java \
src/ca/mitmaro/imdb/entity/Movie.java \
src/ca/mitmaro/imdb/Application.java \
src/ca/mitmaro/imdb/ImdbCommandLine.java \
src/IMDB.java
